name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Pack with Webpack
        run: npm run pack
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'